---
- name: GET DEVICE FAMILY
  hosts: all
  gather_facts: no
  connection: network_cli

  tasks:
  - name: GET DEVICE FAMILY
    include_role:
      name: get_device_family

  - name: LOOKUP IN CSV FILE
    include_role:
      name: lookup_csv_info
    when: "'./excel/test.csv is defined'"

  - name: EXECUTE SCRIPT NXOS
    include_tasks: ./tasks/script_nxos.yaml
    when: "OSFOUND == 'nxos'"

  - name: EXECUTE SCRIPT CSR1000V
    include_tasks: ./tasks/script_ios.yaml
    when: "OSFOUND == 'ios'"

  - name: EXECUTE SCRIPT IOS-XR
    include_tasks: ./tasks/script_ios_xr.yaml
    when: "OSFOUND == 'ios-xr'"
