---
- name: GET FACTS NAPALM DEVICE MODEL
  napalm_get_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      dev_os: iosxr
      filter: ['facts']
  register: ios_xr1
  #when: "OSFOUND == 'ios-xr'"

- debug: var=napalm_facts.model

#- name: SET FACT OF CHASSI MODEL
#  set_fact: ios_xr_model="{{ napalm_model }}"
#  when: "OSFOUND == 'ios-xr'"

#- debug: var=ios_xr_model
