---
- name: GET FACTS NAPALM DEVICE MODEL
  napalm_get_facts:
      hostname: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_password }}"
      dev_os: "{{ OSFOUND }}"
  when: "OSFOUND == 'nxos'"

- name: SET FACT OF CHASSI MODEL
  set_fact: nxosmodel="{{ napalm_model }}"
  when: "OSFOUND == 'nxos'"

- debug: var=nxosmodel
