---
- name: TEMPLATE CSR1000V
  template:
    src: ./template/script_ios.j2
    dest: ./template/configuration/script_{{ inventory_hostname }}_iosxe.conf
  with_items: "{{ inventory_hostname }}"
  when:
    - "'./excel/test.csv is defined'"
    - "OSFOUND == 'ios'"
