---
- name: GATHER OS via SNMP
  snmp_device_version:
    host: "{{ inventory_hostname }}"
    community: public
    version: 2c
  register: output

- set_fact: OSFOUND="{{output.ansible_facts.ansible_device_os}}"

- debug: var=OSFOUND

- name: EXECUTE SCRIPT NXOS
  include_tasks: ./tasks/device_nxos.yaml
  when: "OSFOUND == 'nxos'"

- name: EXECUTE SCRIPT IOS
  include_tasks: ./tasks/device_ios.yaml
  when: "OSFOUND == 'ios'"

- name: EXECUTE SCRIPT IOS-XR
  include_tasks: ./tasks/device_ios_xr.yaml
  when: "OSFOUND == 'ios-xr'"
